server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userMicroservice
    username: root
    password: Damak@0987
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

